version: '3'

services:
  homepage:
    volumes:
      - /Volumes/1tb:/mnt/1tb
      - /Volumes/4tb:/mnt/4tb

  jellyfin:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - /Volumes/4tb/movies:/data/media/movies
      - /Volumes/4tb/shows:/data/media/shows

  prowlarr:
    environment:
      - PGID=20
      - PUID=503

  qbittorrent:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - /Volumes/1tb/torrents:/data/torrents

  radarr:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - /Volumes/1tb/torrents:/data/torrents
      - /Volumes/4tb/movies:/data/media/movies

  sonarr:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - /Volumes/1tb/torrents:/data/torrents
      - /Volumes/4tb/shows:/data/media/shows

  syncthing:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - ~/sync:/data/sync

  unpackerr:
    environment:
      - PGID=20
      - PUID=503
    volumes:
      - /Volumes/1tb/torrents:/data/torrents
