version: '3'

secrets:
  jira_auth_token:
    file: ./mosura/jira_auth_token
  jira_auth_user:
    file: ./mosura/jira_auth_user
  jira_domain:
    file: ./mosura/jira_domain
  jira_label_okr:
    file: ./mosura/jira_label_okr
  jira_other_projects:
    file: ./mosura/jira_other_projects
  jira_project:
    file: ./mosura/jira_project
  jira_team:
    file: ./mosura/jira_team

services:
  caddy:
    container_name: caddy
    image: quay.io/thekevjames/caddy-security:2.7.6-1.1.22
    command: caddy run --config /config/caddy/Caddyfile --adapter caddyfile
    restart: unless-stopped
    env_file:
      - ./secrets/google.env
    volumes:
      - ./caddy:/config/caddy:Z

  # TODO: configure ssh tunneling
  # TODO: consider https://github.com/linuxserver/docker-mods/tree/universal-cloudflared
  cloudflared:
    container_name: cloudflared
    image: docker.io/cloudflare/cloudflared:2024.2.1@sha256:60e94a8669dccbe461b6913ce33ab759104334220b49042ec03cfca62a2f01e7
    command: tunnel run
    restart: unless-stopped
    volumes:
      - ./cloudflared:/home/nonroot/.cloudflared:Z

  docker-socket-proxy:
    container_name: docker-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
      - SERVICES=0
      - TASKS=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fava:
    container_name: fava
    image: quay.io/thekevjames/fava:1.27.2
    command: /data/finance/index.beancount
    restart: unless-stopped
    volumes:
      - /mnt/4tb/sync/finance:/data/finance

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v0.8.8
    restart: unless-stopped
    volumes:
      - /mnt/1tb:/mnt/1tb
      - /mnt/4tb:/mnt/4tb
      - ./homepage:/app/config:Z

  jellyfin:
    container_name: jellyfin
    image: quay.io/linuxserver.io/jellyfin:10.8.13
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/movies:/data/media/movies
      - /mnt/4tb/shows:/data/media/shows
      - ./jellyfin:/config:Z

  mosura:
    container_name: mosura
    image: quay.io/thekevjames/mosura:latest
    restart: unless-stopped
    environment:
      - MOSURA_APPDATA=/data
      - MOSURA_HEADER_USER_EMAIL=X-Token-User-Email
      - MOSURA_PORT=8080
    secrets:
      - jira_auth_token
      - jira_auth_user
      - jira_domain
      - jira_label_okr
      - jira_other_projects
      - jira_project
      - jira_team
    volumes:
      - ./mosura:/data:Z

  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:2024.02.2
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8888:80
    restart: unless-stopped
    environment:
      - DNSMASQ_LISTENING=all
      - TZ=Etc/UTC
    volumes:
      - ./pihole/config:/etc/pihole:Z
      - ./pihole/dnsmasq:/etc/dnsmasq.d:Z

  prowlarr:
    container_name: prowlarr
    image: quay.io/linuxserver.io/prowlarr:1.13.3
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - ./prowlarr:/config:Z

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-4.5.5
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - ./qbittorrent:/config:Z

  radarr:
    container_name: radarr
    image: quay.io/linuxserver.io/radarr:5.3.6
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/movies:/data/media/movies
      - ./radarr:/config:Z

  sonarr:
    container_name: sonarr
    image: quay.io/linuxserver.io/sonarr:4.0.2
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/shows:/data/media/shows
      - ./sonarr:/config:Z

  syncthing:
    container_name: syncthing
    image: quay.io/linuxserver.io/syncthing:1.27.4
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/sync:/data/sync
      - ./syncthing:/config:Z

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr:release-0.12.0
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - ./unpackerr:/config:Z
