## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/plugin/go.d/collector/prometheus#readme

jobs:
  - name: atc1441
    url: 'http://192.168.1.75:9091/metrics'
  - name: caddy
    url: 'http://caddy:2019/metrics'
  - name: cloudflared
    url: 'http://cloudflared:20241/metrics'
  - name: jellyfin
    url: 'http://jellyfin:8096/metrics'
  - name: n8n
    url: 'http://n8n:5678/metrics'
